name: "Code Scanning"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

      - name: Install ESLint TypeScript dependencies
        run: npm install --save-dev @typescript-eslint/eslint-plugin @typescript-eslint/parser

      - name: Run ESLint
        run: |
          npm run lint -- --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload ESLint results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
        if: always()

      - name: Check if SARIF file exists
        id: check-sarif
        run: |
          if [ -f eslint-results.sarif ]; then
            echo "sarif-exists=true" >> $GITHUB_OUTPUT
          else
            echo "sarif-exists=false" >> $GITHUB_OUTPUT
            echo "Creating empty SARIF file"
            echo '{"version": "2.1.0", "runs": []}' > eslint-results.sarif
          fi

      - name: Upload SARIF file
        if: steps.check-sarif.outputs.sarif-exists == 'true' || always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          checkout_path: /home/runner/work/F.I.X.E.S/F.I.X.E.S
          wait-for-processing: true
