name: Handle PR Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  handle-approval:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved' && startsWith(github.event.pull_request.head.ref, 'auto-fix/')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto-merge approved PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch
